name: advance_pdf_viewer_example
description: Demonstrates how to use the advance_pdf_viewer_fork plugin.
publish_to: 'none'

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  advance_pdf_viewer_fork:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - assets/sample.pdf
    - assets/sample2.pdf