name: advance_pdf_viewer_fork
description: A flutter plugin for handling PDF files. Works on both Android & iOS
version: 2.0.1
homepage: https://github.com/cyc2303/pdf_viewer

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=3.16.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_cache_manager: ^3.3.1
  numberpicker: ^2.1.2
  path_provider: ^2.1.2

flutter:
  plugin:
    platforms:
      android:
        package: pt.tribeiro.flutter_plugin_pdf_viewer
        pluginClass: FlutterPluginPdfViewerPlugin
      ios:
        pluginClass: FlutterPluginPdfViewerPlugin
